# Generated by Django 3.2 on 2023-11-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_list',
            old_name='product',
            new_name='ProductList',
        ),
    ]
