# Generated by Django 3.2 on 2023-11-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_product_orders_list_productlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_list',
            old_name='ProductList',
            new_name='products',
        ),
    ]
