# Generated by Django 3.2 on 2023-11-16 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 10, 23, 56, 852176)),
        ),
    ]
