# Generated by Django 3.2 on 2023-11-25 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productlist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 25, 10, 13, 19, 449878)),
        ),
    ]
